### ISSUE TITLE
Pretty JSON for `dyn scan`

### ISSUE THREAD

**Issue by phstc** [rlister/awful#3]
Would be cool :heart: if `dyn scan` could return a pretty JSON:

``` ruby
# https://github.com/rlister/awful/blob/master/lib/awful/dynamodb.rb#L95
# fd.puts JSON.generate(item)
fd.puts JSON.pretty_generate(item)
```

**Comment by buccolo** [comment]
@phstc Alternative `dyn scan table | jq`.

`brew install jq` for that, it's like a query system for json, pretty handy.

**Comment by phstc** [comment]
@buccolo :heart_eyes:
